version: '3.8'

services:
  en-offline-bot:
    build: .
    container_name: en_offline_bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATA_FILE=/app/data/user_data.json
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      # Постоянное хранение данных пользователей
      - bot_data:/app/data
    networks:
      - bot_network
    # Healthcheck для мониторинга
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  bot_data:
    driver: local

networks:
  bot_network:
    driver: bridge